services:
  evrinoma.contractor.factory:
    class: Evrinoma\ContractorBundle\Factory\ContractorFactory
    public: true
    arguments:

  evrinoma.contractor.repository:
    class: Evrinoma\ContractorBundle\Repository\ContractorRepository
    public: true
    arguments:

  evrinoma.contractor.command.manager:
    class: Evrinoma\ContractorBundle\Manager\CommandManager
    arguments:
      - '@evrinoma.contractor.validator'
      - '@evrinoma.contractor.repository'
      - '@evrinoma.contractor.factory'
      - '@evrinoma.contractor.command.mediator'

  evrinoma.contractor.query.manager:
    class: Evrinoma\ContractorBundle\Manager\QueryManager
    arguments:
      - '@evrinoma.contractor.repository'

  Evrinoma\ContractorBundle\Mediator\QueryMediator:
    alias: evrinoma.contractor.query.mediator

  evrinoma.contractor.query.mediator:
    class: Evrinoma\ContractorBundle\Mediator\QueryMediator
    public: true
    arguments:

  Evrinoma\ContractorBundle\Mediator\CommandMediator:
    alias: evrinoma.contractor.command.mediator

  evrinoma.contractor.command.mediator:
    class: Evrinoma\ContractorBundle\Mediator\CommandMediator
    public: true
    arguments:

  Evrinoma\ContractorBundle\Controller\ContractorApiController:
    alias: evrinoma.contractor.api.controller
    public: true

  evrinoma.contractor.api.controller:
    class: Evrinoma\ContractorBundle\Controller\ContractorApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.contractor.command.manager'
      - '@evrinoma.contractor.query.manager'
    autowire: true

  evrinoma.contractor.validator:
    class: Evrinoma\ContractorBundle\Validator\ContractorValidator
    public: true
    arguments:
