services:
  evrinoma.contractor.factory:
    class: Evrinoma\ContractorBundle\Factory\ContractorFactory
    public: true
    arguments:

  evrinoma.contractor.repository:
    class: Evrinoma\ContractorBundle\Repository\ContractorRepository
    public: true
    arguments:

  evrinoma.contractor.command.manager:
    alias: Evrinoma\ContractorBundle\Manager\CommandManager
    public: true

  Evrinoma\ContractorBundle\Manager\CommandManager:
    arguments:
      - '@validator'
      - '@evrinoma.contractor.repository'
      - '@evrinoma.contractor.factory'

  evrinoma.contractor.query.manager:
    alias: Evrinoma\ContractorBundle\Manager\QueryManager
    public: true

  Evrinoma\ContractorBundle\Manager\QueryManager:
    arguments:
      - '@evrinoma.contractor.repository'

  Evrinoma\ContractorBundle\Controller\ContractorApiController:
    alias: evrinoma.contractor.api.controller
    public: true

  evrinoma.contractor.api.controller:
    class: Evrinoma\ContractorBundle\Controller\ContractorApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.contractor.command.manager'
      - '@evrinoma.contractor.query.manager'
    autowire: true

  Evrinoma\ContractorBundle\Provider\BaseProvider:
    alias: evrinoma.contractor.api.provider.base
    public: true

  evrinoma.contractor.api.provider.base:
    class: Evrinoma\ContractorBundle\Provider\BaseProvider
    autowire: true

