services:
  evrinoma.contractor.constraint.property.identity:
    class: Evrinoma\ContractorBundle\Constraint\Property\Identity

  evrinoma.contractor.constraint.property.dependency:
    class: Evrinoma\ContractorBundle\Constraint\Property\Dependency

  evrinoma.contractor.constraint.property.name:
    class: Evrinoma\ContractorBundle\Constraint\Property\Name

  evrinoma.contractor.constraint.property.active:
    class: Evrinoma\ContractorBundle\Constraint\Property\Active


